name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '* * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Make HTTP request and create JSON
      run: |
          RESPONSE=$(curl https://api.runelite.net/session/count)
          
          cat > sessions.json << EOF
          {
            "schemaVersion": 1,
            "label": "sessions",
            "message": "$RESPONSE",
            "color": "orange"
          }
          EOF

    - name: Upload JSON artifact
      uses: actions/upload-artifact@v3
      with:
          name: formatted-data
          path: output.json
          retention-days: 7

    - name: Display result
      run: |
          echo "JSON file created successfully:"
          cat sessions.json
    - name: Commit and push if changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Sessions online ${timestmap}" || exit 0
        git push
